create table if not exists public.google_sheet_requests (
  id bigint generated by default as identity primary key,
  source text not null check (source in ('timed','training')),
  source_row integer not null check (source_row > 1),
  requested_at timestamptz not null,
  requester_name text not null,
  sector text,
  job_title text,
  training_topic text,
  source_status text,
  dashboard_status text not null check (
    dashboard_status in ('completed','pending','not_completed','scheduled','not_scheduled')
  ),
  sort_priority smallint not null default 3,
  row_hash text not null,
  sync_marker uuid not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source, source_row)
);

create table if not exists public.google_sheet_sync_state (
  source text primary key check (source in ('timed','training')),
  status text not null default 'idle' check (status in ('idle','running','success','error')),
  last_attempt_at timestamptz,
  last_success_at timestamptz,
  last_error_at timestamptz,
  last_error_message text,
  locked_at timestamptz,
  lock_expires_at timestamptz,
  execution_id uuid,
  records_processed integer not null default 0,
  duration_ms integer,
  updated_at timestamptz not null default now()
);

create table if not exists public.google_sheet_sync_logs (
  id bigint generated by default as identity primary key,
  source text not null check (source in ('timed','training')),
  execution_id uuid not null,
  started_at timestamptz not null default now(),
  finished_at timestamptz,
  status text not null check (status in ('running','success','error','skipped')),
  records_processed integer not null default 0,
  error_message text,
  duration_ms integer,
  created_at timestamptz not null default now(),
  unique (source, execution_id)
);

create table if not exists public.google_sheet_dashboard_snapshots (
  source text primary key check (source in ('timed','training')),
  total_count integer not null default 0,
  completed_count integer not null default 0,
  pending_count integer not null default 0,
  not_started_count integer not null default 0,
  snapshot_hash text not null,
  snapshot_version bigint not null default 1,
  integration_status text not null default 'not_ready'
    check (integration_status in ('online','delayed','offline','not_ready')),
  cutoff_at timestamptz not null,
  last_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.google_sheet_sync_state(source)
values ('timed'),('training')
on conflict (source) do nothing;

create index if not exists google_sheet_requests_source_status_idx
  on public.google_sheet_requests(source, sort_priority, requested_at desc);
create index if not exists google_sheet_requests_source_requested_idx
  on public.google_sheet_requests(source, requested_at desc);
create index if not exists google_sheet_sync_logs_started_idx
  on public.google_sheet_sync_logs(started_at desc);

alter table public.google_sheet_requests enable row level security;
alter table public.google_sheet_sync_state enable row level security;
alter table public.google_sheet_sync_logs enable row level security;
alter table public.google_sheet_dashboard_snapshots enable row level security;

revoke all on public.google_sheet_requests from anon,authenticated;
revoke all on public.google_sheet_sync_state from anon,authenticated;
revoke all on public.google_sheet_sync_logs from anon,authenticated;
revoke all on public.google_sheet_dashboard_snapshots from anon,authenticated;
grant all on public.google_sheet_requests to service_role;
grant all on public.google_sheet_sync_state to service_role;
grant all on public.google_sheet_sync_logs to service_role;
grant all on public.google_sheet_dashboard_snapshots to service_role;
grant usage,select on sequence public.google_sheet_requests_id_seq to service_role;
grant usage,select on sequence public.google_sheet_sync_logs_id_seq to service_role;

create or replace function public.acquire_google_sheet_sync(
  p_source text,
  p_execution_id uuid,
  p_lock_seconds integer default 110
) returns boolean
language plpgsql security definer
set search_path=public,pg_temp as $$
declare acquired boolean;
begin
  update public.google_sheet_sync_state
     set status='running',
         last_attempt_at=now(),
         locked_at=now(),
         lock_expires_at=now()+make_interval(secs=>greatest(30,p_lock_seconds)),
         execution_id=p_execution_id,
         updated_at=now()
   where source=p_source
     and (lock_expires_at is null or lock_expires_at < now() or execution_id=p_execution_id)
  returning true into acquired;
  return coalesce(acquired,false);
end; $$;

create or replace function public.finish_google_sheet_sync(
  p_source text,
  p_execution_id uuid,
  p_success boolean,
  p_records_processed integer,
  p_duration_ms integer,
  p_error_message text default null
) returns boolean
language plpgsql security definer
set search_path=public,pg_temp as $$
declare changed boolean;
begin
  update public.google_sheet_sync_state
     set status=case when p_success then 'success' else 'error' end,
         last_success_at=case when p_success then now() else last_success_at end,
         last_error_at=case when p_success then null else now() end,
         last_error_message=case when p_success then null else left(p_error_message,300) end,
         records_processed=greatest(0,p_records_processed),
         duration_ms=greatest(0,p_duration_ms),
         locked_at=null,
         lock_expires_at=null,
         execution_id=null,
         updated_at=now()
   where source=p_source and execution_id=p_execution_id
  returning true into changed;
  return coalesce(changed,false);
end; $$;

create or replace function public.prune_google_sheet_requests(
  p_source text,
  p_sync_marker uuid,
  p_cutoff_at timestamptz
) returns integer
language plpgsql security definer
set search_path=public,pg_temp as $$
declare affected integer;
begin
  delete from public.google_sheet_requests
   where source=p_source
     and requested_at >= p_cutoff_at
     and sync_marker <> p_sync_marker;
  get diagnostics affected = row_count;
  return affected;
end; $$;

revoke all on function public.acquire_google_sheet_sync(text,uuid,integer) from public,anon,authenticated;
revoke all on function public.finish_google_sheet_sync(text,uuid,boolean,integer,integer,text) from public,anon,authenticated;
revoke all on function public.prune_google_sheet_requests(text,uuid,timestamptz) from public,anon,authenticated;
grant execute on function public.acquire_google_sheet_sync(text,uuid,integer) to service_role;
grant execute on function public.finish_google_sheet_sync(text,uuid,boolean,integer,integer,text) to service_role;
grant execute on function public.prune_google_sheet_requests(text,uuid,timestamptz) to service_role;

create or replace function private.invoke_google_sheets_sync()
returns bigint language plpgsql security definer
set search_path=private,public,vault,extensions,net,pg_temp as $$
declare project_url text; service_key text; request_id bigint;
begin
  select decrypted_secret into project_url from vault.decrypted_secrets
   where name='gestao_ti_project_url' order by created_at desc limit 1;
  select decrypted_secret into service_key from vault.decrypted_secrets
   where name='gestao_ti_service_role_key' order by created_at desc limit 1;
  if nullif(project_url,'') is null or nullif(service_key,'') is null then return null; end if;
  select net.http_post(
    url:=rtrim(project_url,'/')||'/functions/v1/google-sheets-sync',
    headers:=jsonb_build_object(
      'Content-Type','application/json',
      'Authorization','Bearer '||service_key
    ),
    body:='{"origin":"supabase_cron"}'::jsonb,
    timeout_milliseconds:=50000
  ) into request_id;
  return request_id;
end; $$;
revoke all on function private.invoke_google_sheets_sync() from public,anon,authenticated;

do $$ declare job record; begin
  for job in select jobid from cron.job where jobname='gestao-ti-google-sheets-sync'
  loop perform cron.unschedule(job.jobid); end loop;
  perform cron.schedule(
    'gestao-ti-google-sheets-sync',
    '* * * * *',
    'select private.invoke_google_sheets_sync()'
  );
end $$;

notify pgrst,'reload schema';
