-- Snapshot público pequeno, produzido exclusivamente pela sincronização GLPI.
-- A tabela contém somente dados operacionais autorizados; raw_payload e dados
-- do solicitante permanecem fora deste contrato.
create table if not exists public.gestao_ti_dashboard_snapshot (
  id bigint generated by default as identity primary key,
  scope text not null default 'daily_public',
  group_id bigint not null,
  shift_start timestamptz not null,
  shift_end timestamptz not null,
  shift_type text not null check (shift_type in ('Diurno', 'Noturno')),
  open_count integer not null default 0 check (open_count >= 0),
  in_progress_count integer not null default 0 check (in_progress_count >= 0),
  waiting_count integer not null default 0 check (waiting_count >= 0),
  pending_count integer not null default 0 check (pending_count >= 0),
  overdue_count integer not null default 0 check (overdue_count >= 0),
  technicians_chart_json jsonb not null default '[]'::jsonb,
  latest_tickets_json jsonb not null default '[]'::jsonb,
  snapshot_hash text not null,
  snapshot_version bigint not null default 1 check (snapshot_version > 0),
  integration_status text not null default 'offline'
    check (integration_status in ('online', 'delayed', 'offline')),
  last_synced_at timestamptz not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (scope, group_id),
  check (jsonb_typeof(technicians_chart_json) = 'array'),
  check (jsonb_typeof(latest_tickets_json) = 'array'),
  check (jsonb_array_length(latest_tickets_json) <= 10)
);

alter table public.gestao_ti_dashboard_snapshot enable row level security;

revoke all on table public.gestao_ti_dashboard_snapshot from public, authenticated;
grant select on table public.gestao_ti_dashboard_snapshot to anon;

drop policy if exists "Public can read sanitized daily snapshot"
  on public.gestao_ti_dashboard_snapshot;
create policy "Public can read sanitized daily snapshot"
  on public.gestao_ti_dashboard_snapshot
  for select
  to anon
  using (scope = 'daily_public');

alter table public.glpi_tickets_dashboard
  add column if not exists solving_technician_id bigint,
  add column if not exists solving_technician_name text;

-- Backfill controlado: extrai somente os dois campos normalizados necessários.
-- O payload bruto continua interno e nunca integra a tabela de snapshot.
update public.glpi_tickets_dashboard
set solving_technician_id = nullif(raw_payload #>> '{_dashboard_solution_technician,id}', '')::bigint,
    solving_technician_name = nullif(raw_payload #>> '{_dashboard_solution_technician,name}', '')
where solving_technician_id is null
  and jsonb_typeof(raw_payload -> '_dashboard_solution_technician') = 'object'
  and coalesce(raw_payload #>> '{_dashboard_solution_technician,id}', '') ~ '^[0-9]+$';

create index if not exists glpi_tickets_dashboard_group_status_idx
  on public.glpi_tickets_dashboard (group_id, status_id);
create index if not exists glpi_tickets_dashboard_group_opened_idx
  on public.glpi_tickets_dashboard (group_id, opened_at desc);
create index if not exists glpi_tickets_dashboard_group_solved_idx
  on public.glpi_tickets_dashboard (group_id, solved_at desc)
  where solved_at is not null;

comment on table public.gestao_ti_dashboard_snapshot is
  'Snapshot sanitizado do Dashboard Diário público; uma linha por grupo e escopo.';
comment on column public.gestao_ti_dashboard_snapshot.snapshot_hash is
  'SHA-256 estável do conteúdo operacional, sem o instante da sincronização.';
